project:
  type: website

website:
  site-url: "https://mcnicol-lab.github.io/ecophilab"
  navbar:
    logo: images/logo/main-logo-notext.png
    left:
      - text: Home
        href: index.qmd
      - text: Projects  
        href: projects.qmd
      - text: People
        href: people.qmd
      - text: Contact
        href: contact.qmd
      - text: About
        href: about.qmd
        
  page-footer:
    left: "© 2025 ecoφlab at UIC"
    right: "Design by J. Nathaly"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false