# **Our Mission**

We ask:

-   *what is a healthy ecosystem?*

-   *what is a healthy planet?*

And perhaps most importantly...

-   *how can we advance ecosystem and planetary health together?*

# Our Name

## eco for ecosystem

Terrestrial ecosystems are our main characters, including wetlands, rainforests, and prairies at field scales. We aim to understand them holistically, from bedrock-to-canopy, using ecosystem concepts of composition, structure, and function. We describe cycles, identify feedback loops, and consider how ecosystem behavior changes across scales via emergence and self-organization.

## p for planetary

Earth's living organisms inhabit ecosystems small relative to our planet, yet, in the words of Arthur Tansley \[*On Ecosystems\]*, " the systems we isolate are not only included as part of larger ones, but they also overlap, interlock, and interact with one another."

Though our work often begins with ecosystems we can readily isolate, our motivations and discoveries reflect a shared concern for planetary habitability.

## h for **health**

Health lacks formal definition and consistent metrics across ecosystem to planetary scales, and yet the benefits of good health are so universally recognized and aspired to that we believe health warrants fuller characterization. With our strengths in quantifying, explaining, and predicting ecosystem function we position ourselves to contribute to future research to improve individual and collective health.

## i for **integration** ∫

Finding the integral of a mathematical function allows us to calculate **stocks, fluxes, and other quantities across space and time**. Metaphorically, it could also be interpreted as a request for personal or professional development, implying a desire to become more integrated or well-rounded in some aspect of life. Socially, to integrate into a group or activity - reflecting our lab's commitment to inclusion.

## φ for **phi**

Phi ("fye", not "fee") is the 21st letter of the Greek alphabet, and is used in mathematics, science, and philosophy. In mathematics, phi (φ) often represents the golden ratio, an irrational number approximately equal to 1.618. In philosophy, phi can symbolize concepts such as harmony, balance, or perfection. As ecophiles, we try to balance empirical observation and experimentation with the *logos* evident in nature.
