---
title: "Join Us"
editor: visual
---

**PI's Statement on Universal Inclusion**

*Humanity may be likened unto the vari-colored flowers of one garden. There is unity in diversity. Each sets off and enhances the other's beauty.*

‘Abdu’l-Bahá, *Divine Philoso*phy, p. 25-26

I am committed to universal inclusion grounded in shared mission. This commitment is rooted in an axiomatic belief; that of the transformative ideal of ***unity in diversity***. This phrasing originated in the writings of ʻAbdu'l-Bahá, who was the son of the visionary founder of the Bahá’í faith, Baháʼu'lláh. I find it apt and inspiring, because it emphasizes the interdependent equality of both diversity and unity, and latent in the phrase there is also a warning that promoted alone, these ideals may seed division or coerce uniformity, respectively.

Our collaborative work as scientists presentations a new forum and opportunity to engage conversations about diversity, equity, and inclusion as ethical ideals, i.e., ***virtues***. I believe promoting universal inclusion grounded in a shared mission is a vehicle to advance this discourse and better realize diversity, equity, and inclusion scientific settings, and to achieve a more unified scientific community.

I maintain **five overarching commitments** to advancing universal inclusion in my management of the Ecosystem and Planetary Health Integration Lab. They are to:

-   Clearly define and communication our scientific mission and invite participation

-   Critically evaluate representation in my group and how diversity may be improved

-   Regularly facilitate group discussions to define inclusive culture and codes of conduct

-   Be universal in respect for individual difference and unique in responses to requests

-   Nurture open and honest discussion, as well as civil and constructive criticism

**Current Openings:**

We are currently seeking Undergraduate Assistants.

**Email:**

gmcnicol \[at\] uic \[dot\] edu

**Mailing Address:**

Departmemt of Earth and Environmental Sciences

845 W Taylor Street,

MC 186

Chicago

IL-60607

U.S.A
