---
title: "Join Us"
editor: visual
---

**PI's Statement on Universal Inclusion**

*Humanity may be likened unto the vari-colored flowers of one garden. There is unity in diversity. Each sets off and enhances the other's beauty.*

‘Abdu’l-Bahá, *Divine Philoso*phy, p. 25-26

I am committed to universal inclusion grounded in shared mission. This commitments is rooted in an axiomatic belief; that of the transformative ideal of ***unity in diversity***. This phrasing originated in the writings ofʻAbdu'l-Bahá, who was the son of the visionary founder of the Bahá’í faith, Baháʼu'lláh. I find itmost apt because it emphasizes the interdependent equality of both diversity and unity. Latent in the phrase, there is also a warning that, promoted alone, these ideals may seed division or coerce uniformity, respectively.

Beyond my own perspective, our present opportunity to engage conversations about diversity, equity, and inclusion in the context of scientific research inspires me profoundly at a personal level, and leaves me anxious to realize these ideals as best I can through my scientific work. I’m inspired personally because I have many times been told that science as an institution is naturally antagonistic to articles of faith, among which are commitments to ethical ideals, i.e., ***virtues***. Indeed, I absorbed this same antagonistic mantra as a graduate student. But, having experienced directly and indirectly, and perceiving broadly, a profound inconsistency between the purported ethics of science and the conduct of scientists and the culture of their institutions, this antagonism left me disillusioned about the potential for science to achieve the cultural changes necessary to resolve these ethical problems.

I now feel a **renewed hope** because I share the belief that we must, as scientists, strive for better personal conduct and collective culture, and a part of this striving demands a deeper reflection of the meaning and purpose of ethical ideals. I believe promoting universal inclusion grounded in a shared mission is a vehicle to advance our discourse of and better realize diversity, equity, and inclusion professional work settings and that it can ultimately lead us down a path to a more unified scientific community.

I maintain **five overarching commitments** to advancing universal inclusion in my management of the Ecosystem and Planetary Health Integration Lab. They are to:

-   Critically evaluate representation in my group and how diversity may be improved

-   Regularly facilitate group discussions to define inclusive culture and codes of conduct

-   Be universal in respect for individual difference and unique in responses to requests

-   Nurture open and honest discussion, as well as civil and constructive criticism

-   Annually re-evaluate and update my commitments as the group evolves

**Current Openings:**

We are currently seeking Undergraduate Assistants.

**Email:**

gmcnicol \[at\] uic \[dot\] edu

**Mailing Address:**

Departmemt of Earth and Environmental Sciences

845 W Taylor Street,

MC 186

Chicago

IL-60607

U.S.A
